# Settings for kubewarden-controller.
nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

image:
  # controller image to be used. Leave empty to use
  # ghcr.io/kubewarden/kubewarden-controller
  repository: ""
  # image tag, leave empty to use chart's AppVersion
  tag: ""

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}


# Policy Server settings
policyServer:
  replicaCount: 1
  image:
    repository: ghcr.io/kubewarden/policy-server
    tag: "v0.1.2"
