apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-server
data:
  replicas: "{{ .Values.policyServer.replicaCount | default 1 }}"
  image: "{{ .Values.policyServer.image.repository  }}:{{ .Values.policyServer.image.tag }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewarden-controller-manager-config
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: a4ddbf36.kubewarden.io

