apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubewarden-controller.fullname" . }}-metrics-service
  labels:
    {{- include "kubewarden-controller.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "kubewarden-controller.selectorLabels" . | nindent 4 }}
