{{ if .Values.recommendedPolicies.enabled }}
apiVersion: {{ $.Values.crdVersion }}
kind: ClusterAdmissionPolicy
metadata:
  labels:
    {{- include "kubewarden-defaults.labels" . | nindent 4 }}
    app.kubernetes.io/component: policy
  annotations:
    {{- include "kubewarden-defaults.annotations" . | nindent 4 }}
  name: {{ $.Values.recommendedPolicies.allowPrivilegeEscalationPolicy.name }}
spec:
  mode: {{ $.Values.recommendedPolicies.defaultPolicyMode }}
  module: '{{ template "system_default_registry" . }}{{ $.Values.recommendedPolicies.allowPrivilegeEscalationPolicy.module }}'
{{ include "policy-namespace-selector" . | indent 2}}
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: true
  settings:
    default_allow_privilege_escalation: false
{{ end }}
