name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Check Helm generated values are up-to-date
        run: |
          make check-generated-values
      - name: Run shellcheck in the shell scripts
        run: |
          make shellcheck
