name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Check Helm generated values are up-to-date
        run: |
          make check-generated-values
      - name: Run shellcheck in the shell scripts
        run: |
          make shellcheck
